In [1]:
text = ["This is a line",
       "This is another line",
       "Completely different line"]

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [15]:
cv = CountVectorizer()

In [16]:
sparse_matrix = cv.fit_transform(text)

In [17]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [18]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [13]:
tfidf = TfidfTransformer()

In [19]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

## Convert BOW to TF-IDF

In [20]:
results = tfidf.fit_transform(sparse_matrix)

In [21]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

## One Step Approach

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
tv = TfidfVectorizer()

In [25]:
tv_results = tv.fit_transform(text)

In [26]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])